export { default as Home } from './Home/Home'
export { default as Trip } from './Trip/Trip'
export { default as Contact } from './Contact/Contact'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as NotFound } from './NotFound/NotFound'
