export { Home } from './Home/Home'
export { NotFound } from './NotFound/NotFound'
export { Profile } from './Profile/Profile'
export { ProductDetail } from './ProductDetail/ProductDetail'
export { Login } from './Login/Login'
